config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :middle_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  protect_from_forgery unless: -> { request.format.json? }

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:code, :class_equipment, :type_equipment, :manufacturer, :platform, :model_number, :os, :total_memory_ram, :processor, :total_storage, :purchase_date, :warranty_expires, :details, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :middle_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipment/_form.html.erb
<%= simple_form_for(@equipment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :class_equipment %>
    <%= f.input :type_equipment %>
    <%= f.input :manufacturer %>
    <%= f.input :platform %>
    <%= f.input :model_number %>
    <%= f.input :os %>
    <%= f.input :total_memory_ram %>
    <%= f.input :processor %>
    <%= f.input :total_storage %>
    <%= f.input :purchase_date %>
    <%= f.input :warranty_expires %>
    <%= f.input :details %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Class equipment</th>
      <th>Type equipment</th>
      <th>Manufacturer</th>
      <th>Platform</th>
      <th>Model number</th>
      <th>Os</th>
      <th>Total memory ram</th>
      <th>Processor</th>
      <th>Total storage</th>
      <th>Purchase date</th>
      <th>Warranty expires</th>
      <th>Details</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= equipment.code %></td>
        <td><%= equipment.class_equipment %></td>
        <td><%= equipment.type_equipment %></td>
        <td><%= equipment.manufacturer %></td>
        <td><%= equipment.platform %></td>
        <td><%= equipment.model_number %></td>
        <td><%= equipment.os %></td>
        <td><%= equipment.total_memory_ram %></td>
        <td><%= equipment.processor %></td>
        <td><%= equipment.total_storage %></td>
        <td><%= equipment.purchase_date %></td>
        <td><%= equipment.warranty_expires %></td>
        <td><%= equipment.details %></td>
        <td><%= equipment.user %></td>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @equipment.code %>
</p>

<p>
  <strong>Class equipment:</strong>
  <%= @equipment.class_equipment %>
</p>

<p>
  <strong>Type equipment:</strong>
  <%= @equipment.type_equipment %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @equipment.manufacturer %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @equipment.platform %>
</p>

<p>
  <strong>Model number:</strong>
  <%= @equipment.model_number %>
</p>

<p>
  <strong>Os:</strong>
  <%= @equipment.os %>
</p>

<p>
  <strong>Total memory ram:</strong>
  <%= @equipment.total_memory_ram %>
</p>

<p>
  <strong>Processor:</strong>
  <%= @equipment.processor %>
</p>

<p>
  <strong>Total storage:</strong>
  <%= @equipment.total_storage %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @equipment.purchase_date %>
</p>

<p>
  <strong>Warranty expires:</strong>
  <%= @equipment.warranty_expires %>
</p>

<p>
  <strong>Details:</strong>
  <%= @equipment.details %>
</p>

<p>
  <strong>User:</strong>
  <%= @equipment.user %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav>
  <%= link_to 'Users', users_path %>
  <%= link_to 'Equipment', equipment_index_path %>
</nav>

<%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :middle_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.middle_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @user.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>